# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: Starfall OS
description: Personal Build Utilizing Kinoite, Bazzite, and Proton App Suite

# Use Kinoite as the base image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # Use "latest" for automatic updates

modules:
  - type: files
    files:
      - source: system
        destination: / # Copies files/system/* into the root folder

  - type: rpm-ostree
    repos:
      # Bazzite repository for gaming kernel and tools
      - https://repo.bazzite.org/fedora/$releasever/x86_64/
      # Zen Browser repository for lightweight browsing
      - https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-$OS_VERSION%/sneexy-zen-browser-fedora-$OS_VERSION%.repo

    install:
      # KDE Plasma minimal setup (already included in Kinoite but can be customized)
      - plasma-desktop
      - dolphin
      - konsole
      
      # Bazzite kernel and gaming tools for optimization
      - kernel-bazzite
      - vkBasalt
      - mangohud
      
      # Zen Browser for lightweight browsing experience
      - zen-browser
      
      # Proton App Suite (Mail, VPN, Calendar, Drive, Pass)
      - protonmail-desktop-beta.rpm
      - protonvpn-stable-release-1.0.3-1.noarch.rpm
      - proton-calendar.rpm
      - proton-drive.rpm
      - protonpass.rpm
      
    remove:
      # Remove Thunderbird in favor of Proton Mail Suite
      - thunderbird

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        # Essential apps for ease of use and neurodivergent-friendly tools
        - com.valvesoftware.Steam # Gaming platform
        - net.lutris.Lutris # Game launcher/manager
        - org.freedesktop.Platform.VulkanLayer.MangoHud
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo # Flathub URL for user-level Flatpaks
      repo-name: flathub # Name of the Flatpak repository

signing:
  type: signing # Sets up policy & signing files for signed images to work fully

alt-tags:
  - lightweight-kde-gaming-os

